### ISSUE TITLE
Server Processing Time

### ISSUE THREAD

**Issue by StephanGeorg** [yosuke-furukawa/httpstat#8]
I'm using httpstat as library in my application. The result contains _begin_, _onLookup_, _onConnect_, _onSecureConnect_, _onTransfer_ and _onTotal_. Would you please explain how you calculate the **Server Processing Time** like in the CLI version? 

```
...
const { time } = result;
console.log(`DNS Lookup ${(time.onLookup - time.begin)}ms`);
console.log(`TCP Connection ${(time.onConnect - time.onLookup)}ms`);
console.log(`SSL Handshake ${(time.onSecureConnect - time.onConnect)}ms`);
console.log(`Content Transfer ${(time.onTransfer - time.begin)}ms`);
console.log(`Server Processing `);
console.log(`Total Time ${(time.onTotal - time.begin)}ms`);
```

Thanks.

**Comment by yosuke-furukawa** [comment]
I am not so clear the `Server Processing Time`.
That is not total time ???
our total time is based on response end time. `res.on('end')` is `onTotal` time.

**Comment by StephanGeorg** [comment]
My question was how you calculate the server processing time in the CLI? 

Stephan Georg
Chief Strategy Officer

-- 
Nearest RWGL UG (haftungsbeschränkt)
Glogauer Straße 5 | 10999 Berlin
Phone: +49 30 95614 663 | Fax: +49 30 95614 664
http://nearest.place | s.georg@nearest.place

Amtsgericht Charlottenburg | HRB 169047
Geschäftsführer: Timo Rütten, Sebastian Wehner, Stephan Georg, Orlando Lieberum
St.Nr.: 29/433/--- | Ust. ID-Nr.: DE-------------

**Comment by yosuke-furukawa** [comment]
Oh I got it.
Server Processing time is difference from "time to connect (or time to secure connect)"  to "time to transfer". 

```
const { time } = result;
console.log(`DNS Lookup ${(time.onLookup - time.begin)}ms`);
console.log(`TCP Connection ${(time.onConnect - time.onLookup)}ms`);
console.log(`SSL Handshake ${(time.onSecureConnect - time.onConnect)}ms`);
console.log(`Server Processing ${(time.onTransfer - time.onSecureConnect)}`);
console.log(`Content Transfer ${(time.onTotal - time.onTransfer)}ms`);
console.log(`Total Time ${(time.onTotal - time.begin)}ms`);
```

**Comment by StephanGeorg** [comment]
Ah, great, thanks. But what's about _Content Transfer_ and _Total Time_:

```
  console.log(`DNS Lookup ${(time.onLookup - time.begin)}ms`);
  console.log(`TCP Connection ${(time.onConnect - time.onLookup)}ms`);
  console.log(`SSL Handshake ${(time.onSecureConnect - time.onConnect)}ms`);
  console.log(`Server Processing ${(time.onTransfer - time.onSecureConnect)}ms`);
  console.log(`Content Transfer `);
  console.log(`Total Time `);
```

**Comment by yosuke-furukawa** [comment]
I said before comment.

```
console.log(`Content Transfer ${(time.onTotal - time.onTransfer)}ms`);
console.log(`Total Time ${(time.onTotal - time.begin)}ms`);
```

**Comment by StephanGeorg** [comment]
Hm? But 
```
console.log(`Content Transfer ${(time.onTotal - time.onTransfer)}ms`);
```
is 1ms every time.

**Comment by yosuke-furukawa** [comment]
It is based on the response data size. `onTrasfer` is calculated when called `req.on('readable')`, but `onTotal` is calculated when called `req.on('end')` .
Here is the logic.

https://github.com/yosuke-furukawa/httpstat/blob/master/lib/reporter.js#L95

**Comment by StephanGeorg** [comment]
Ok, thanks for clarification.
