### ISSUE TITLE
Nothing gets printed out

### ISSUE THREAD

**Issue by oncletom** [yosuke-furukawa/httpstat#9]
I tried this command and nothing gets printed out:

```bash
$ npx httpstat https://github.com/
npx: installed 3 in 1.501s

```

Do you have any idea why?

**Comment by yosuke-furukawa** [comment]
please tell me your node.js version. v10?

**Comment by oncletom** [comment]
It happens both on Node 8 and Node 10.

**Comment by yosuke-furukawa** [comment]
hm, Node.js v10 changed the event flow.

https://github.com/nodejs/node/issues/21398

the issue is reproduced. I will fix it.

**Comment by yosuke-furukawa** [comment]
v1.5.1 is released. please try again.

**Comment by oncletom** [comment]
Amazing, it works 🙂 

Is it due to a change of behaviour of streams?

Thanks so much for fixing the module 👍
